---
# Role: install_rsat
# Description: Installs RSAT tools for Windows from a ZIP file


- name: Copy PowerShell script to enable Windows Update service
  win_copy:
    content: |
      Set-Service -Name wuauserv -StartupType Manual
      Start-Service -Name wuauserv
    dest: C:\Windows\temp\enable_windows_update.ps1

- name: Enable Windows Update service
  win_shell: C:\Windows\temp\enable_windows_update.ps1
  args:
    executable: powershell.exe

- name: Verify Windows Update service is running
  win_service:
    name: wuauserv
    state: started

- name: Display Windows edition
  debug:
    var: ansible_os_product_type

- block:
  - name: Install RSAT Tools with PowerShell (Server)
    ansible.windows.win_feature:
      name: RSAT-AD-PowerShell
      state: present
    vars:
      ansible_become: true
      ansible_become_method: runas
      ansible_become_user: '.\localuser'
      ansible_become_password: 'password'
      ansible_become_flags: "logon_type=interactive logon_flags=netcredentials_only"
    #async: 120
    #poll: 0
    register: win_feature
  
  - name: Reboot if installing RSAT feature requires it
    ansible.windows.win_reboot:
    when: win_feature.reboot_required
  when: ansible_os_product_type is search("server")

- block:
  - name: Install RSAT Tools with PowerShell (Workstation)
    ansible.windows.win_powershell:
      script: |
        Get-WindowsCapability -Name Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0 -Online | Add-WindowsCapability -Online
    vars:
     ansible_become: true
     ansible_become_method: runas
     ansible_become_user: '.\localuser'
     ansible_become_password: 'password'
     ansible_become_flags: "logon_type=interactive logon_flags=netcredentials_only"
  when: ansible_os_product_type is search("workstation")

- name: Clean up temporary files
  win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - C:\Windows\temp\enable_windows_update.ps1
